modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="emerald_sword"
version="1.0.0"
displayName="Emerald Sword"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="minec, MCreator"

[[dependencies.emerald_sword]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



